alias: Smart Charge - Phone
description: ""
trigger:
  - platform: state
    to: Single
    entity_id:
      - select.smart_charger_button1_sensor
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.smart_charge_automation_state_phone
    data: {}
  - type: turn_on
    device_id: cd6201a28582884b6863d705f942b8aa
    entity_id: switch.smart_charger_relay_1
    domain: switch
  - wait_for_trigger:
      - type: plugged_in
        platform: device
        device_id: 3d82accdc8154de3a8a857b903735273
        entity_id: binary_sensor.mha_l09_is_charging
        domain: binary_sensor
    continue_on_timeout: true
    timeout: "4"
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.mha_l09_is_charging
            state: "on"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: sensor.mha_l09_battery_state
                from: charging
                to: full
          - type: turn_off
            device_id: cd6201a28582884b6863d705f942b8aa
            entity_id: switch.smart_charger_relay_1
            domain: switch
          - service: notify.chris_devices
            data:
              title: Charge Complete
              message: Phone has completed charging
      - conditions:
          - condition: state
            entity_id: binary_sensor.mha_l09_is_charging
            state: "off"
        sequence:
          - type: turn_off
            device_id: cd6201a28582884b6863d705f942b8aa
            entity_id: switch.smart_charger_relay_1
            domain: switch
          - wait_template: ""
            timeout: "0.5"
            continue_on_timeout: true
          - repeat:
              count: "3"
              sequence:
                - type: turn_on
                  device_id: cd6201a28582884b6863d705f942b8aa
                  entity_id: switch.smart_charger_led_1
                  domain: switch
                - wait_template: ""
                  timeout: "0.5"
                - type: turn_off
                  device_id: cd6201a28582884b6863d705f942b8aa
                  entity_id: switch.smart_charger_led_1
                  domain: switch
                - wait_template: ""
                  timeout: "0.5"
    default: []
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.smart_charge_automation_state_phone
    data: {}
mode: single
max: 10